# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2023-10-15 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20231015_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecies',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, to='pokemon.PokemonTypes'),
        ),
    ]
