# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2023-11-16 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20231015_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PokemonAdmin',
        ),
        migrations.DeleteModel(
            name='PokemonSpeciesAdmin',
        ),
        migrations.DeleteModel(
            name='PokemonTrainersAdmin',
        ),
        migrations.DeleteModel(
            name='PokemonTypesAdmin',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='id',
            new_name='pokemon_id',
        ),
        migrations.RenameField(
            model_name='pokemonspecies',
            old_name='id',
            new_name='species_id',
        ),
        migrations.RenameField(
            model_name='pokemontrainers',
            old_name='id',
            new_name='trainer_id',
        ),
        migrations.RenameField(
            model_name='pokemontypes',
            old_name='id',
            new_name='type_id',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='shard_id',
            field=models.CharField(default='server_1', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='shard_id',
            field=models.CharField(default='server_1', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemontrainers',
            name='shard_id',
            field=models.CharField(default='server_1', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemontypes',
            name='shard_id',
            field=models.CharField(default='server_1', max_length=50),
        ),
    ]
